



# Path to database
db_path: "/home/kenrickmh/CHEM/dft-mixing-plugin/example_usage/func_database.db"

# Flag to recreate databse from scratch. 
recreate_db: False

# Sources with lower index means higher priority.
external_resol: ["src1"]


