
db_path: "/home/kenrickmh/CHEM/dft-mixing-plugin/scf_lcom/scripts/database/example_databases"

# Sources with lower index means higher priority.
external_resol: ['src1', 'src2']

# Adapter configurations
dftd3_config: "/home/kenrickmh/CHEM/dft-mixing-plugin/database/sdftd3_ref_params.toml"
load_dftd3: True
