###############################################
#          INITIALIZATION CONFIGURATION
#
###############################################


# Path to database
db_path: "/home/kenrickmh/CHEM/dft-mixing-plugin/example_usage/database/func_database.db"

# Sources with lower index means higher priority.
external_resol: ["src1"]

# Path to dftd3 toml file (temporary)
dftd3_config: "/home/kenrickmh/CHEM/dft-mixing-plugin/example_usage/compile_database/sdftd3_ref_params.toml"
load_dftd3: True

# Database Preloading Data (IN ORDER from TOP to BOTTOM)
# This is only read if database is reloaded from scratch
# Params for each entry:
# source: grouping name for functionals
# type: type of data, either of ['mf', 'dc', 'bd']
#         'MF': Multi Functional
#         'DC': Dispersion Configuration (dispersion mixing/multidispersion)
#         'BD': Dispersion Base (contains params)
preload:
  - source: 'src1'
    type: 'MF'
    json_path:  /home/kenrickmh/CHEM/dft-mixing-plugin/example_usage/compile_database/multifunc.json
  - source: 'src1'
    type: 'BD'
    json_path:  /home/kenrickmh/CHEM/dft-mixing-plugin/example_usage/compile_database/base_disp.json
  - source: 'src1'
    type: 'DC'
    json_path:  /home/kenrickmh/CHEM/dft-mixing-plugin/example_usage/compile_database/disp_config.json
